from .trainer import *
#from .detect_trainer import DetectTrainer
#from .box_detect_trainer import BoxDetectTrainer
#from .box_pair_trainer import BoxPairTrainer
#from .graph_pair_trainer import GraphPairTrainer
#from .feature_pair_trainer import FeaturePairTrainer
#from .lf_trainer import LFTrainer
#from .pix_with_feats_trainer import PixWithFeatsTrainer
#from .toy_graph_trainer import ToyGraphTrainer
from .hw_with_style_trainer import HWWithStyleTrainer
from .hwr_with_synth_trainer import HWRWithSynthTrainer
from .spacing_trainer import SpacingTrainer
from .auto_trainer import AutoTrainer
